name: Build Check

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  makeTest:
    strategy:
      matrix:
        runs-on-os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on-os }}
    container:
      image: quay.io/rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v7
      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=github-release" >> $GITHUB_ENV
      - name: Test Makefile Targets
        run: ci/testbuilding.sh

  buildTest-x86-64:
    needs: makeTest
    uses: ./.github/workflows/build-matrix.yml
    with:
      runs-on: ubuntu-latest
      arch: x86_64
      specifictarget: github-release

  buildTest-arm:
    needs: makeTest
    uses: ./.github/workflows/build-matrix.yml
    with:
      runs-on: ubuntu-24.04-arm
      arch: aarch64
      specifictarget: github-release

  mockTest:
    needs: makeTest
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.runner }}
    container:
      image: quay.io/rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v7

      - name: Test Mock Build From Spec
        run: |
          dnf -y install epel-release
          dnf -y install mock gcc gcc-c++ glibc-devel libdrm-devel rpm-build make wget
          usermod -a -G mock root
          make srpm-github
          mock -r rocky+epel-9-${{ matrix.arch }} --define="_github 1" --spec="displaylink.spec" --sources="."
