name: Devel Branch Build

on:
  schedule:
    - cron: '30, 5, *, *, 1'

jobs:
  develBuild:
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: fedora
            version: 29
            dockernamespace: fedora
          - os: fedora
            version: 30
            dockernamespace: fedora
          - os: fedora
            version: 31
            dockernamespace: fedora
          - os: fedora
            version: 32
            dockernamespace: fedora
          - os: fedora
            version: 33
            dockernamespace: fedora
          - os: fedora
            version: 34
            dockernamespace: fedora
          - os: fedora
            version: 35
            dockernamespace: fedora
          - os: fedora
            version: 36
            dockernamespace: fedora
          - os: centos
            version: 7.9.2009
            dockernamespace: centos
          - os: centos-stream
            version: stream8
            dockernamespace: quay.io/centos/centos
          - os: rocky
            version: 8
            dockernamespace: rockylinux

    steps:
      - uses: actions/checkout@v2

      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=devel" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV

      - name: Run CI
        run: ci/${{ matrix.os }}.sh
