name: Main Branch Build

on:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  mainBuild-x86-64:
    uses: ./.github/workflows/build-matrix.yml
    with:
      runs-on: ubuntu-latest
      arch: x86_64
      specifictarget: main

  mainBuild-arm:
    uses: ./.github/workflows/build-matrix.yml
    with:
      runs-on: ubuntu-24.04-arm
      arch: aarch64
      specifictarget: main
