name: Create Release Assets

on:
  release:
    types:
      - published
      - edited

jobs:
  build-srpm:
    runs-on: ubuntu-latest
    container:
      image: quay.io/rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v7

      - name: Get version
        run: echo "VERSION=$(sed -n 's/^VERSION[[:space:]]*:=[[:space:]]*//p' Makefile)" >> $GITHUB_ENV

      - name: Get release
        run: echo "RELEASE=$(sed -n 's/^RELEASE[[:space:]]*:=[[:space:]]*//p' Makefile)" >> $GITHUB_ENV

      - name: Set environment variables
        run: echo "SPECIFICTARGET=srpm-github" >> $GITHUB_ENV

      - name: Build SRPM
        run: ci/rocky.sh

      - name: Upload SRPM to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'displaylink-${{ env.VERSION }}-${{ env.RELEASE }}*.src.rpm'
          draft: false
          update_latest_release: true
          tags: true
          overwrite: true

  buildrpms-x86-64:
    uses: ./.github/workflows/build-matrix.yml
    with:
      runs-on: ubuntu-latest
      arch: x86_64
      specifictarget: rpm-github
      upload: true
    secrets: inherit

  buildrpms-arm:
    uses: ./.github/workflows/build-matrix.yml
    with:
      runs-on: ubuntu-24.04-arm
      arch: aarch64
      specifictarget: rpm-github
      upload: true
    secrets: inherit
